export const data = [
  {
    id: "1",
    templateID: "templateNow",
    title: "Page Current Weather",
    prefix: "weather",
    friendlyUrl: "current-weather/location",
    language: "english",
  },
  {
    id: "2",
    templateID: "templateHourly",
    title: "Page Hourly",
    prefix: "weather",
    friendlyUrl: "hourly-forecast/today",
    language: "english",
  },
  {
    id: "3",
    templateID: "templateSevenDays",
    title: "Page 7 Days",
    prefix: "weather",
    friendlyUrl: "7-days/list",
    language: "english",
  },
  {
    id: "4",
    templateID: "templateMeteoGram",
    title: "Page Meteo Gram",
    prefix: "weather",
    friendlyUrl: "7-days/meteogram",
    language: "english",
  },
  {
    id: "5",
    templateID: "templateSatellite",
    title: "Page Satellite",
    prefix: "weather",
    friendlyUrl: "live-satellite",
    language: "english",
  },
  {
    id: "6",
    templateID: "templateMaps",
    title: "Page Maps",
    prefix: "weather",
    friendlyUrl: "maps/storm",
    language: "english",
  },
  {
    id: "6",
    templateID: "templateHistory",
    title: "Page History",
    prefix: "weather",
    friendlyUrl: "history/daily-history",
    language: "english",
  },
  {
    id: "7",
    templateID: "templateNow",
    title: "Thời tiết hiện tại",
    prefix: "weather",
    friendlyUrl: "current-weather/location",
    language: "vietnamese",
  },
  {
    id: "8",
    templateID: "templateHourly",
    title: "Thời tiết theo giờ",
    prefix: "weather",
    friendlyUrl: "hourly-forecast/today",
    language: "vietnamese",
  },
  {
    id: "9",
    templateID: "templateSevenDays",
    title: "Thời tiết 7 ngày",
    prefix: "weather",
    friendlyUrl: "7-days/list",
    language: "vietnamese",
  },
  {
    id: "10",
    templateID: "templateMeteoGram",
    title: "Khí tượng học",
    prefix: "weather",
    friendlyUrl: "7-days/meteogram",
    language: "vietnamese",
  },
  {
    id: "11",
    templateID: "templateSatellite",
    title: "Vệ tinh trực tiếp",
    prefix: "weather",
    friendlyUrl: "live-satellite",
    language: "vietnamese",
  },
  {
    id: "12",
    templateID: "templateMaps",
    title: "Bản đồ thời tiết",
    prefix: "weather",
    friendlyUrl: "maps/storm",
    language: "vietnamese",
  },
  {
    id: "13",
    templateID: "templateHistory",
    title: "Lịch sử thời tiết",
    prefix: "weather",
    friendlyUrl: "history/daily-history",
    language: "vietnamese",
  },
];
